# Generated by Django 2.2.2 on 2019-07-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('supplier', '0002_auto_20190718_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='product_name')),
                ('buying_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('s_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category')),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
        ),
    ]
