# Generated by Django 2.2.2 on 2019-07-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdetails',
            options={'verbose_name_plural': 'StockDetails'},
        ),
        migrations.AlterModelTable(
            name='stockdetails',
            table='stock_db',
        ),
    ]
