# Generated by Django 2.2.2 on 2019-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190718_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='buying_rate',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='selling_rate',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
