# Generated by Django 2.2.2 on 2019-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190719_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetails',
            name='s_date',
            field=models.DateField(),
        ),
    ]
