# Generated by Django 2.2.2 on 2019-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('mobile', models.IntegerField(max_length=10, verbose_name='Mobile')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customer_db',
            },
        ),
    ]
