# Generated by Django 2.2.2 on 2019-07-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
    ]
